language: cpp
dist: xenial
compiler:
  - gcc

git:
  quiet: true

addons:
  apt:
    packages:
      - libxml++2-dev
      - libxslt1-dev
      - libwebkit2gtk-4.0-dev
      - libofx-dev
      - xsltproc
      - libdbi-dev
      - libdbd-sqlite3
      - libsecret-1-dev
      - guile-2.0-dev
      - libboost-all-dev
 
before_script:
  - export APP=GnuCash
  - export LOWERAPP=${APP,,}
  - export APPDIR="$TRAVIS_BUILD_DIR/AppDir"
  - mkdir --parents ${APPDIR}/usr

script:
  #=== Get App sources:
  - chmod a+x ./jq-linux64
  - echo "TRAVIS_TAG = ${TRAVIS_TAG}"
  - GITHUB_RELEASE=$([ -z "${TRAVIS_TAG}" ] && echo "latest" || echo "tags/${TRAVIS_TAG}")
  - GITHUB_REST=$(curl https://api.github.com/repos/GnuCash/gnucash/releases/${GITHUB_RELEASE})
  - wget --quiet $(echo "${GITHUB_REST}" | ./jq-linux64 ".assets | map(select(.content_type == \"application/gzip\"))[0].browser_download_url" | sed s/\"//g)
  - tar xf gnucash-*.tar.gz
  #=== Compile:
  - bash ./${APP}.compileApp.sh
  - export VERSION=$(ls gnucash-*.tar.gz | sed -r 's/.*gnucash-(.*).tar.gz/\1/')
  - echo "VERSION = ${VERSION}"
  - tar -czf ${APP}_AppDir.tar.gz $APPDIR
  #=== Build AppImage:
  - wget --quiet https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
  - chmod a+x linuxdeployqt-continuous-x86_64.AppImage
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  - ./linuxdeployqt-continuous-x86_64.AppImage ${APPDIR}/usr/share/applications/*.desktop -appimage

after_success:
  - find ${APPDIR} -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh ${APP}*.AppImage*
  - bash upload.sh ${APP}_AppDir.tar.gz

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
