name: AppImage Build
on:
  release:
    types: [created, edited]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag'
        required: true

jobs:
  build:
    #ubuntu bionic:
    runs-on: ubuntu-18.04
  
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@master
  
    # Runs a single command using the runners shell
    - name: Install required dependencies
      run: sudo apt-get --reinstall install --yes wget patchelf librsvg2-dev cmake libxslt-dev xsltproc ninja-build libboost-all-dev libgtk-3-dev guile-2.2-dev libgwengui-gtk3-dev libaqbanking-dev libofx-dev libdbi-dev libdbd-sqlite3 libwebkit2gtk-4.0-dev googletest swig language-pack-en language-pack-fr
  
    # Runs a set of commands using the runners shell
    - name: Executing AppImage build
      run: bash ./make_appimage.sh
  
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: True
        tag: ${{ github.event.inputs.tag }}
        name: "Release build (${{ github.event.inputs.tag }})"
        artifacts: "GnuCash*.AppImage"
        token: ${{ secrets.GITHUB_TOKEN }}
